version: '3.9'

services:
  db:
    image: mysql:8
    restart: on-failure
    env_file: .env
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_ROOT_HOST: '%'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d
    command:
      --default-authentication-plugin=mysql_native_password
      --init-file /docker-entrypoint-initdb.d/init.sql
    networks:
      nw:
        ipv4_address: 172.28.1.2
  django:
    build: 
      context: .
      dockerfile: ./docker/django/Dockerfile
    restart: unless-stopped
    ports:
      - "${WEB_PORT:-8000}:8000"
    environment:
      DB_DATABASE: $DB_DATABASE
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_IP: 172.28.1.2
      SERVER_IP: ${SERVER_IP} # exportada desde github actions en el servidor
    depends_on:
      - db
    networks:
      nw:
        ipv4_address: 172.28.1.1

volumes:
  mysql_data:

networks:
  nw:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16