# Generated by Django 4.2.1 on 2023-05-11 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='last_session',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
