# Generated by Django 4.2.1 on 2023-05-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_users_last_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.TextField(blank=True, choices=[('carnes', 'Carnes'), ('lacteos', 'Lacteos'), ('pan', 'Pan'), ('carniceria', 'Carniceria'), ('panaderia', 'Panaderia'), ('despensa', 'Despensa'), ('botilleria', 'Botilleria'), ('frutas_verduras', 'Frutas o Verduras'), ('limpieza', 'Limpieza')], default='despensa', null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_type',
            field=models.TextField(blank=True, choices=[('negocio_pequeño', 'Negocio de Barrio'), ('panaderia', 'Panaderia'), ('verduleria', 'Verduleria'), ('carniceria', 'Carniceria'), ('mini_market', 'MiniMarket')], default='negocio_pequeño', null=True),
        ),
    ]
