# Generated by Django 4.1.7 on 2023-03-18 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_finance_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='open_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
