# Generated by Django 4.2.1 on 2023-05-29 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_supplier_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.shop'),
        ),
        migrations.DeleteModel(
            name='ShopItems',
        ),
    ]
