# Generated by Django 4.2.1 on 2023-05-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_item_shop_delete_shopitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='opens_at',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
