# Generated by Django 4.2.1 on 2023-06-01 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_shop_opens_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sold',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
