# Generated by Django 4.2.1 on 2023-06-01 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_item_sold_alter_item_quantity_alter_item_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.TextField(blank=True, choices=[('lacteos', 'Lacteos'), ('carniceria', 'Carniceria'), ('panaderia', 'Panaderia'), ('despensa', 'Despensa'), ('botilleria', 'Botilleria'), ('frutas_verduras', 'Frutas o Verduras'), ('limpieza', 'Limpieza'), ('mascota', 'Mascotas')], default='despensa', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='sold',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
