# Generated by Django 4.2.1 on 2023-06-01 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_category_category_alter_item_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
