# Generated by Django 4.2.1 on 2023-06-01 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_item_quantity_alter_item_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='buy_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='sell_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
