# Generated by Django 4.2.1 on 2023-06-01 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_item_buy_price_alter_item_sell_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='categories',
            new_name='categories_id',
        ),
    ]
