# Generated by Django 4.2.1 on 2023-06-01 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_users_finance_finance_users_finance_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='shop_id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sold',
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.TextField(blank=True, choices=[('lacteos', 'Lacteos'), ('carniceria', 'Carniceria'), ('panaderia', 'Panaderia'), ('despensa', 'Despensa'), ('botilleria', 'Botilleria'), ('frutas_verduras', 'Frutas o Verduras'), ('limpieza', 'Limpieza'), ('mascotas', 'Mascotas')], default='despensa', null=True),
        ),
        migrations.CreateModel(
            name='ShopItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_update', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('sold', models.IntegerField(blank=True, default=0, null=True)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('weight', models.IntegerField(blank=True, default=0, null=True)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('item_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopitems', to='api.item')),
                ('shop_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopitems', to='api.shop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='item',
            name='shop',
            field=models.ManyToManyField(blank=True, through='api.ShopItems', to='api.shop'),
        ),
    ]
