# Generated by Django 4.2.1 on 2023-06-02 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_item_shop_id_remove_item_sold_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopitems',
            old_name='quantity',
            new_name='quantity_sold',
        ),
        migrations.RenameField(
            model_name='shopitems',
            old_name='sold',
            new_name='total_sold',
        ),
        migrations.RenameField(
            model_name='shopitems',
            old_name='weight',
            new_name='weight_sold',
        ),
    ]
