# Generated by Django 4.2.1 on 2023-06-11 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_quantity_shopitems_quantity_sold_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtorItemSold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_update', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('quantity_debtor', models.FloatField(blank=True, null=True)),
                ('weight_debtor', models.FloatField(blank=True, null=True)),
                ('total_debtor', models.FloatField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShopItemSold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_update', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('total_sold', models.IntegerField(blank=True, default=0, null=True)),
                ('quantity_sold', models.IntegerField(blank=True, default=0, null=True)),
                ('weight_sold', models.IntegerField(blank=True, default=0, null=True)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='finance',
            name='users_finance_id',
        ),
        migrations.RemoveField(
            model_name='shopitems',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='shopitems',
            name='shop_id',
        ),
        migrations.RemoveField(
            model_name='userdebtoritems',
            name='debtors_id',
        ),
        migrations.RemoveField(
            model_name='userdebtoritems',
            name='items_id',
        ),
        migrations.RemoveField(
            model_name='userdebtoritems',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='debtor',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='categories_id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='city',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='commune',
        ),
        migrations.RemoveField(
            model_name='userfinances',
            name='finance_id',
        ),
        migrations.AddField(
            model_name='debtor',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debtor', to='api.shop'),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.TextField(blank=True, choices=[('lacteos', 'Lacteos'), ('carniceria', 'Carniceria'), ('panaderia', 'Panaderia'), ('despensa', 'Despensa'), ('botilleria', 'Botilleria'), ('frutas_verduras', 'Frutas o Verduras'), ('limpieza', 'Limpieza'), ('mascotas', 'Mascotas')], default='despensa', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='shop_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='api.shop'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Finance',
        ),
        migrations.DeleteModel(
            name='ShopItems',
        ),
        migrations.DeleteModel(
            name='UserDebtorItems',
        ),
        migrations.AddField(
            model_name='shopitemsold',
            name='item_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopitemsold', to='api.item'),
        ),
        migrations.AddField(
            model_name='shopitemsold',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopitemsold', to='api.shop'),
        ),
        migrations.AddField(
            model_name='debtoritemsold',
            name='debtors_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interdebtors', to='api.debtor'),
        ),
        migrations.AddField(
            model_name='debtoritemsold',
            name='items_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interitems', to='api.item'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_sold',
            field=models.ManyToManyField(blank=True, related_name='item_sold', through='api.ShopItemSold', to='api.shop'),
        ),
    ]
