# Generated by Django 4.2.1 on 2023-06-11 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_supplier_user_id_supplier_shop_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopFinances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_update', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('type', models.TextField(blank=True, choices=[('profit', 'Ganancia'), ('cost', 'Gasto')], default='profit', null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('shop_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopfinances', to='api.shop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='UserFinances',
        ),
    ]
