# Generated by Django 4.2.1 on 2023-06-13 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_shopfinances_delete_userfinances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitemsold',
            name='item_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopitemsold', to='api.item'),
        ),
    ]
