# Generated by Django 4.2.1 on 2023-06-13 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_item_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='type',
            new_name='measure',
        ),
    ]
