# Generated by Django 4.2.1 on 2023-06-13 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_rename_type_item_measure'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillDebtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_update', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('total_bill', models.IntegerField(blank=True, default=0, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('debtors_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='api.debtor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_update', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('quantity_debtor', models.IntegerField(blank=True, null=True)),
                ('weight_debtor', models.IntegerField(blank=True, null=True)),
                ('current_price', models.IntegerField(blank=True, null=True)),
                ('bill_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billitem', to='api.billdebtor')),
                ('items_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billitem', to='api.item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='DebtorItemSold',
        ),
    ]
