# Generated by Django 4.2.1 on 2023-06-14 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_billdebtor_billitem_delete_debtoritemsold'),
    ]

    operations = [
        migrations.AddField(
            model_name='billdebtor',
            name='items',
            field=models.ManyToManyField(related_name='bills', through='api.BillItem', to='api.item'),
        ),
    ]
