# Generated by Django 4.2.1 on 2023-06-14 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_billdebtor_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billdebtor',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='bills', through='api.BillItem', to='api.item'),
        ),
    ]
