# Generated by Django 4.2.1 on 2023-06-22 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_shop_image_file_alter_users_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/user/images/'),
        ),
    ]
