name: deploy

on:
  push:
    branches: 
      - actions-test
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: actions-test
      - name: install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: compose down
        working-directory: /home/${{ secrets.SSH_USER }}/server
        run: |
          if [ -f docker-compose.yml ]; then
            docker-compose down
          else
            echo "No existe el archivo docker-compose.yml"
          fi
      - name: rsync
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: .
          remote_path: /home/${{ secrets.SSH_USER }}/server
          remote_host: ${{ secrets.SERVER_IP }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_KEY }}
      - name: compose up
        working-directory: /home/${{ secrets.SSH_USER }}/server
        run: |
          if [ -f docker-compose.yml ]; then
            docker-compose up --build --detach
          else
            echo "No existe el archivo docker-compose.yml"
          fi
      
        

      
